 INSERT INTO "scanEngine_enginetype" (engine_name, yaml_configuration, default_engine, scan_type) VALUES ('Custom - Full Stack CVE Scanner', '# ============================================================            +
 #  CUSTOM FULL STACK CVE SCANNER  -- pt-zenity                                                                                                                                                                         +
 #  Next.js + Laravel + Livewire + Swagger + React + Generic                                                                                                                                                            +
 #  Custom nuclei templates: 29 templates                                                                                                                                                                               +
 #  Cocok untuk: bug bounty modern web apps                                                                                                                                                                             +
 # ============================================================                                                                                                                                                         +
                                                                                                                                                                                                                        +
 scan_type: ''bug_bounty''                                                                                                                                                                                              +
 timeout: 8                                                                                                                                                                                                             +
 threads: 50                                                                                                                                                                                                            +
 rate_limit: 150                                                                                                                                                                                                        +
                                                                                                                                                                                                                        +
 custom_header: {                                                                                                                                                                                                       +
   ''User-Agent'': ''Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0'',                                                                                                                          +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 subdomain_discovery: {                                                                                                                                                                                                 +
   ''uses_tools'': [''subfinder'', ''ctfr'', ''tlsx''],                                                                                                                                                                 +
   ''threads'': 50,                                                                                                                                                                                                     +
   ''timeout'': 5,                                                                                                                                                                                                      +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 http_crawl: {                                                                                                                                                                                                          +
   ''threads'': 50,                                                                                                                                                                                                     +
   ''precrawl_batch_size'': 400,                                                                                                                                                                                        +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 vulnerability_scan: {                                                                                                                                                                                                  +
   ''run_nuclei'': true,                                                                                                                                                                                                +
   ''run_dalfox'': false,                                                                                                                                                                                               +
   ''run_crlfuzz'': false,                                                                                                                                                                                              +
   ''run_s3scanner'': false,                                                                                                                                                                                            +
   ''concurrency'': 80,                                                                                                                                                                                                 +
   ''intensity'': ''normal'',                                                                                                                                                                                           +
   ''rate_limit'': 150,                                                                                                                                                                                                 +
   ''retries'': 1,                                                                                                                                                                                                      +
   ''timeout'': 8,                                                                                                                                                                                                      +
   ''fetch_llm_report'': false,                                                                                                                                                                                         +
   ''nuclei'': {                                                                                                                                                                                                        +
     ''use_nuclei_config'': false,                                                                                                                                                                                      +
     ''severities'': [''medium'', ''high'', ''critical''],                                                                                                                                                              +
     ''templates'': [                                                                                                                                                                                                   +
       ''http/custom/nextjs'',                                                                                                                                                                                          +
       ''http/custom/laravel'',                                                                                                                                                                                         +
       ''http/custom/livewire'',                                                                                                                                                                                        +
       ''http/custom/swagger'',                                                                                                                                                                                         +
       ''http/custom/react'',                                                                                                                                                                                           +
       ''http/custom/generic'',                                                                                                                                                                                         +
     ],                                                                                                                                                                                                                 +
   }                                                                                                                                                                                                                    +
 }', false, 'bug_bounty');
 INSERT INTO "scanEngine_enginetype" (engine_name, yaml_configuration, default_engine, scan_type) VALUES ('Custom - Laravel+Livewire Deep Scan', '# ============================================================        +
 #  LARAVEL + LIVEWIRE DEEP SCAN  -- pt-zenity                                                                                                                                                                          +
 #  Khusus untuk aplikasi Laravel/Livewire                                                                                                                                                                              +
 #  Mencakup: env exposure, debug RCE, telescope,                                                                                                                                                                       +
 #  horizon, storage, routes, livewire SSRF+RCE                                                                                                                                                                         +
 # ============================================================                                                                                                                                                         +
                                                                                                                                                                                                                        +
 scan_type: ''bug_bounty''                                                                                                                                                                                              +
 timeout: 8                                                                                                                                                                                                             +
 threads: 40                                                                                                                                                                                                            +
 rate_limit: 150                                                                                                                                                                                                        +
                                                                                                                                                                                                                        +
 custom_header: {                                                                                                                                                                                                       +
   ''User-Agent'': ''Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0'',                                                                                                                          +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 http_crawl: {                                                                                                                                                                                                          +
   ''threads'': 40,                                                                                                                                                                                                     +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 vulnerability_scan: {                                                                                                                                                                                                  +
   ''run_nuclei'': true,                                                                                                                                                                                                +
   ''run_dalfox'': false,                                                                                                                                                                                               +
   ''run_crlfuzz'': false,                                                                                                                                                                                              +
   ''run_s3scanner'': false,                                                                                                                                                                                            +
   ''concurrency'': 60,                                                                                                                                                                                                 +
   ''intensity'': ''normal'',                                                                                                                                                                                           +
   ''rate_limit'': 150,                                                                                                                                                                                                 +
   ''retries'': 1,                                                                                                                                                                                                      +
   ''timeout'': 8,                                                                                                                                                                                                      +
   ''fetch_llm_report'': false,                                                                                                                                                                                         +
   ''nuclei'': {                                                                                                                                                                                                        +
     ''use_nuclei_config'': false,                                                                                                                                                                                      +
     ''severities'': [''medium'', ''high'', ''critical''],                                                                                                                                                              +
     ''templates'': [                                                                                                                                                                                                   +
       ''http/custom/laravel'',                                                                                                                                                                                         +
       ''http/custom/livewire'',                                                                                                                                                                                        +
       ''http/misconfiguration/laravel-debug-enabled.yaml'',                                                                                                                                                            +
       ''http/misconfiguration/laravel-debug-error.yaml'',                                                                                                                                                              +
       ''http/misconfiguration/laravel-horizon-unauth.yaml'',                                                                                                                                                           +
       ''http/misconfiguration/laravel-sessions-exposure.yaml'',                                                                                                                                                        +
       ''http/misconfiguration/laravel-terminal-exposure.yaml'',                                                                                                                                                        +
       ''http/exposures/configs/laravel-env.yaml'',                                                                                                                                                                     +
       ''http/exposures/logs/laravel-log-file.yaml'',                                                                                                                                                                   +
       ''http/exposures/logs/laravel-telescope.yaml'',                                                                                                                                                                  +
       ''http/cves/2021/CVE-2021-3129.yaml'',                                                                                                                                                                           +
     ],                                                                                                                                                                                                                 +
   }                                                                                                                                                                                                                    +
 }', false, 'bug_bounty');
 INSERT INTO "scanEngine_enginetype" (engine_name, yaml_configuration, default_engine, scan_type) VALUES ('Custom - Next.js+React Security Audit', '# ============================================================      +
 #  NEXT.JS + REACT SECURITY AUDIT  -- pt-zenity                                                                                                                                                                        +
 #  CVE-2025-29927 middleware bypass, source map,                                                                                                                                                                       +
 #  env leak, API routes enum, Redux state, XSS                                                                                                                                                                         +
 # ============================================================                                                                                                                                                         +
                                                                                                                                                                                                                        +
 scan_type: ''bug_bounty''                                                                                                                                                                                              +
 timeout: 8                                                                                                                                                                                                             +
 threads: 40                                                                                                                                                                                                            +
 rate_limit: 150                                                                                                                                                                                                        +
                                                                                                                                                                                                                        +
 custom_header: {                                                                                                                                                                                                       +
   ''User-Agent'': ''Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0'',                                                                                                                          +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 http_crawl: {                                                                                                                                                                                                          +
   ''threads'': 40,                                                                                                                                                                                                     +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 vulnerability_scan: {                                                                                                                                                                                                  +
   ''run_nuclei'': true,                                                                                                                                                                                                +
   ''run_dalfox'': false,                                                                                                                                                                                               +
   ''run_crlfuzz'': false,                                                                                                                                                                                              +
   ''run_s3scanner'': false,                                                                                                                                                                                            +
   ''concurrency'': 60,                                                                                                                                                                                                 +
   ''intensity'': ''normal'',                                                                                                                                                                                           +
   ''rate_limit'': 150,                                                                                                                                                                                                 +
   ''retries'': 1,                                                                                                                                                                                                      +
   ''timeout'': 8,                                                                                                                                                                                                      +
   ''fetch_llm_report'': false,                                                                                                                                                                                         +
   ''nuclei'': {                                                                                                                                                                                                        +
     ''use_nuclei_config'': false,                                                                                                                                                                                      +
     ''severities'': [''medium'', ''high'', ''critical''],                                                                                                                                                              +
     ''templates'': [                                                                                                                                                                                                   +
       ''http/custom/nextjs'',                                                                                                                                                                                          +
       ''http/custom/react'',                                                                                                                                                                                           +
       ''http/custom/generic'',                                                                                                                                                                                         +
       ''http/cves/2025/CVE-2025-29927.yaml'',                                                                                                                                                                          +
     ],                                                                                                                                                                                                                 +
   }                                                                                                                                                                                                                    +
 }', false, 'bug_bounty');
 INSERT INTO "scanEngine_enginetype" (engine_name, yaml_configuration, default_engine, scan_type) VALUES ('Custom - API Security (Swagger+GraphQL+JWT)', '# ============================================================+
 #  API SECURITY SCANNER  -- pt-zenity                                                                                                                                                                                  +
 #  Swagger/OpenAPI exposure, GraphQL introspection,                                                                                                                                                                    +
 #  JWT none algorithm, CORS misconfiguration,                                                                                                                                                                          +
 #  API endpoint enumeration                                                                                                                                                                                            +
 # ============================================================                                                                                                                                                         +
                                                                                                                                                                                                                        +
 scan_type: ''bug_bounty''                                                                                                                                                                                              +
 timeout: 8                                                                                                                                                                                                             +
 threads: 50                                                                                                                                                                                                            +
 rate_limit: 200                                                                                                                                                                                                        +
                                                                                                                                                                                                                        +
 custom_header: {                                                                                                                                                                                                       +
   ''User-Agent'': ''Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0'',                                                                                                                          +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 http_crawl: {                                                                                                                                                                                                          +
   ''threads'': 50,                                                                                                                                                                                                     +
 }                                                                                                                                                                                                                      +
                                                                                                                                                                                                                        +
 vulnerability_scan: {                                                                                                                                                                                                  +
   ''run_nuclei'': true,                                                                                                                                                                                                +
   ''run_dalfox'': false,                                                                                                                                                                                               +
   ''run_crlfuzz'': false,                                                                                                                                                                                              +
   ''run_s3scanner'': false,                                                                                                                                                                                            +
   ''concurrency'': 80,                                                                                                                                                                                                 +
   ''intensity'': ''normal'',                                                                                                                                                                                           +
   ''rate_limit'': 200,                                                                                                                                                                                                 +
   ''retries'': 1,                                                                                                                                                                                                      +
   ''timeout'': 8,                                                                                                                                                                                                      +
   ''fetch_llm_report'': false,                                                                                                                                                                                         +
   ''nuclei'': {                                                                                                                                                                                                        +
     ''use_nuclei_config'': false,                                                                                                                                                                                      +
     ''severities'': [''medium'', ''high'', ''critical''],                                                                                                                                                              +
     ''templates'': [                                                                                                                                                                                                   +
       ''http/custom/swagger'',                                                                                                                                                                                         +
       ''http/custom/generic'',                                                                                                                                                                                         +
       ''http/technologies/graphql-detect.yaml'',                                                                                                                                                                       +
     ],                                                                                                                                                                                                                 +
   }                                                                                                                                                                                                                    +
 }', false, 'bug_bounty');

